### PR TITLE
feat: filter users by firstname

### PR DESCRIPTION
**Pull request by aarbanas**
## Description

Add firstname input search on users table.

### CODE REVIEW

**Comment by imiljancic** [comment]
@aarbanas I found the issue for the re-renders and missing value in the search input. We're going to have to do a little bit of refactoring regarding the component/page itself.

The main issue is on the following line `if (!data) return <LoadingSpinner />;`. When you enter a value to the search that triggers the API call, the line I've sent will be an early exit which will cause the whole table, search input, etc, to get deleted from the DOM and painted anew. Which in the end causes the SearchInput to lose its state.

I would suggest that we move the loading spinner into the table itself since this will mean that the whole page will always be there and only the loading spinner/table will be toggled between and not the whole page.

**Comment by aarbanas** [comment]
> @aarbanas I found the issue for the re-renders and missing value in the search input. We're going to have to do a little bit of refactoring regarding the component/page itself.
> 
> The main issue is on the following line `if (!data) return <LoadingSpinner />;`. When you enter a value to the search that triggers the API call, the line I've sent will be an early exit which will cause the whole table, search input, etc, to get deleted from the DOM and painted anew. Which in the end causes the SearchInput to lose its state.
> 
> I would suggest that we move the loading spinner into the table itself since this will mean that the whole page will always be there and only the loading spinner/table will be toggled between and not the whole page.

Great catch 🚀

**Comment by aarbanas** [comment]
There was an issue with debounce because for tRPC debounce must return a promise. https://github.com/TanStack/query/issues/293

**Review by imiljancic — APPROVED** [review]
LGTM!

**Pull request merged**
